version: '3'
services:
  db:
    container_name: neo4j_container
    image: neo4j:4.4.26
    env_file: .env
    ports:
      - 7474:7474
      - 7687:7687
    volumes: 
      - volume_db:/var/lib/neo4j/data
volumes:
  volume_db:
    name: vneo4j
