version: '3.6'
services:
  db:
    container_name: neo4j_container
    image: neo4j:4.4.26-enterprise
    env_file: .env
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - type: volume
        source: volume_db
        target: /data
volumes:
  volume_db:
    name: vneo4j
